### PR TITLE
@tus/server: add allowedCredentials and allowedOrigins options

### PR DESCRIPTION
**Pull request by idanto**
Hi,

Uppy client supports `withCredentials` parameter to allow sending tokens in cookie
https://uppy.io/docs/tus/#withcredentials

Tus Server doesn't allow any way to configure it; it seems like a missing configuration, and this MR is a suggestion on how to implement it.

### CODE REVIEW

**Comment by Acconut** [comment]
Should the user also be able to enable this only for requests from certain origins? Allowing it from arbitrary origins is potentially dangerous.

**Comment by idanto** [comment]
> Should the user also be able to enable this only for requests from certain origins? Allowing it from arbitrary origins is potentially dangerous.

@Acconut, isn't that what Access-Control-Allow-Origin should do in the CORS policy?

TBH, I don't see a way to limit it in Tus code. I see the opposite which looks like the client can override it by sending an origin header.

**Comment by Acconut** [comment]
If tus-node-server does not yet have a way to restrict CORS access to certain origins, then we should probably add that as well.

**Comment by idanto** [comment]
@Murderlon I agree in general, but this is a special case. Those are CORS options, which is a well-defined standard. In most of the server implementations, I know you usually have specific options to configure your CORS to prevent people from making mistakes (like typos and so on).

**Comment by Murderlon** [comment]
My experience is that sooner or later people run into the limitations of these locked down options. For example, people with preview deployments, where the subdomain is dynamic, will not be able to use `string[]` for their origins.

If we make it `RegExp | string[]` I'm okay with keeping the options as proposed 👍

**Comment by Murderlon** [comment]
@idanto are you still interested in getting this over the finish line?

**Comment by idanto** [comment]
@Murderlon looks like after you merge master everything is green

**Comment by Murderlon** [comment]
Only this needs to be resolved: https://github.com/tus/tus-node-server/pull/636#issuecomment-2257764146.

I can take a look later this week if you don't have time before then.

**Comment by Murderlon** [comment]
Thanks for the contribution

**Comment by idanto** [comment]
thanks for the help pushing it to the finish line @Murderlon

**Pull request merged**
