### PR TITLE
MongoDB GridFS Backend Implementation

### PR DESCRIPTION
**Pull request by genixpro**
I have created an implementation of DataStore that uses MongoDB as its backing client.

Please provide me your comments & changes soon. I would love to be able to get this out into the main line release so I don't have to link to my own fork.

### CODE REVIEW

**Comment by kvz** [comment]
Hi, Thanks for this! I'm not the project owner so I'll refrain from going in depth, but one thing i noticed at first glance was a different notation for if statements across this pr. Consider:

 - https://github.com/tus/tus-node-server/pull/58/files#diff-5832d2dac09e5cb3a316c47d2c1dad6aR42
 - https://github.com/tus/tus-node-server/pull/58/files#diff-5832d2dac09e5cb3a316c47d2c1dad6aR125

This raises the question if we are/shouldbe enforcing coding standards for this project. If we aren't yet, I have some good experiences with http://standardjs.com/. Most of the standard can be automatically applied via `eslint --fix`. Not having semicolons takes a week of getting used to, but the linting prevents you from fatal mistakes that could potentially happen by leaving them out.

**Comment by genixpro** [comment]
Yes I use ESLint in my other projects. Its a good tool. This project has different standards then what I use and I converted everything at the end. Clearly missed a few spots, I can fix that up.

**Comment by kvz** [comment]
That would be great, thank you so much!

**Comment by bhstahl** [comment]
Thanks for your work @genixpro ! I'll look into why the travis builds are failing on the keyfile decryption before even reaching eslint checks

**Comment by genixpro** [comment]
Hello, I have come back and made a few bug fixes after some testing. But I am having difficulty using the eslint configuration for this project. It seems to be referencing some module created by vimeo, as I get the error:

Error: Cannot find module '@vimeo/eslint-config-player/es6'

**Comment by bhstahl** [comment]
Hey @genixpro, do you have any trouble when running `npm install @vimeo/eslint-config-player` ? Also what version of node are you running?

```sh
$ node -v
v4.4.4
```

[4.4.4](https://github.com/tus/tus-node-server/blob/master/package.json#L26) was the last LTS version, which is pinned in the `package.json` but we can probably bump that to the current LTS (6.9.2) If needed.

**Comment by bhstahl** [comment]
Hey @genixpro, rebasing master should get you a successful travis build (see [Build #210](https://travis-ci.org/tus/tus-node-server/builds/183572533)).

**Comment by nemox** [comment]
Is this MongoDB Backend implemented? If so, where can I find the docs ?

**Comment by Acconut** [comment]
@nemox No, this feature is not available in the master versions. The work on this PR seems to have been stalled, so we couldn't merge it yet.

**Pull request closed without merging**
