### PR TITLE
Close event handler on request

### PR DESCRIPTION
**Pull request by sirakoff**
When upload is aborted, the writeStream doesn't end. So the file cannot be altered or deleted.

### CODE REVIEW

**Comment by bhstahl** [comment]
Good catch @sirakoff !

If you could fix the errors in the travis build, and (possibly add a test?) I'll merge and bump the version. Thanks a bunch

**Comment by bhstahl** [comment]
Hey @sirakoff that openssl build error should be resolved in master, let me know if you have any trouble adding a test for this. When you do, i'll merge and bump 👍

**Comment by bhstahl** [comment]
Also if you could remove the changes that only add/reorder lines, that would be ideal

**Comment by bhstahl** [comment]
Hey @sirakoff, rebasing master should get you a successful travis build (see [Build #210](https://travis-ci.org/tus/tus-node-server/builds/183572533)).

**Comment by Murderlon** [comment]
Closing this as it's supersedes by #188

**Pull request closed without merging**
