### PR TITLE
Fix memory leaks on interrupted upload

### PR DESCRIPTION
**Pull request by mitjap**
When connection is closed by client (for example when pausing an upload), promise is never settled, which causes memory leak. This issue is present in FileStore and GCSDataStore (not sure about S3Store). In case of FileStore files might stay in write mode and locked.

When using `.pipe()` not all events are connected, so I switched it to new `stream.pipeline(source, destination, cb)`. 

This was inspired by #34.

### CODE REVIEW

**Comment by Acconut** [comment]
Nice catch! i didn´t know `stream.pipe` could be dangerous and that there is a `stream.pipeline` method to work around this.

**Comment by ErunamoJAZZ** [comment]
oh god, this would explain those memory leaks I got in a project sometime ago :S

**Review by Murderlon — APPROVED** [review]
Needs a merge from master but other than that this seems good to go

**Comment by Murderlon** [comment]
Thanks!

**Pull request merged**
