### PR TITLE
Allow `Authorization` header. Closes #99

### LINKED ISSUE #99: basic authentication through a HTTPS proxy
Hi, for this, I had to add the `Authorization` header to `lib/constants.js`, and also the corresponding function in `lib/validators/RequestValidator.js`:

```javascript
static _invalidAuthorizationHeader(value) {
    return false;
}
```

It works in my test environment, but I don't have direct access to the production server to use custom codes.

Could this be included in the master branch? Then I could ask for a server update. Than you!

### PR DESCRIPTION
**Pull request by rictorres**
This will allow requests with `Authorization` present on their headers.

### CODE REVIEW

**Comment by rictorres** [comment]
gcs e2e tests are failing. @bhstahl could you help pleaase?

**Comment by Acconut** [comment]
These GCS test failures also appear in the master branch, so I presume they are unrelated. So let's get this thing merged! Thank you very much

**Comment by calmdev** [comment]
Any chance of getting this published to npm?

**Comment by Acconut** [comment]
Yes, there will be a 0.3.0 soonish.

**Pull request merged**
