### PR TITLE
Add protocol to location header in POSTs

### PR DESCRIPTION
**Pull request by erikhandersson**
The protocol in the location header was missing in POST
requests. The protocol is present in tusd.

### CODE REVIEW

**Comment by kvz** [comment]
Good catch @erikhandersson! I wonder if we should loosen up the protocol instead tho in this regard. Interested to hear what @Acconut thinks of this. IIRC there was talk once about officially supporting completely relative paths (so `/files/xxx`) but perhaps we never poured that into protocol. Something slightly different than allowing protocol-relative paths (so `//example.com/files/xxx`) but perhaps worth discussing explicitly allowing both in the protocol as it seems it might solve some problems for people implementing it in the different infra scenarios out there

**Comment by Acconut** [comment]
The protocol was originally not presented in the URL to let browsers make the decision whether to use HTTPS or HTTP, similar to how you can write `<script src="//myhost.com/script.js></script>` and the browser will pick the corresponding protocol. I believe this worked well for browsers but not other platforms (e.g. Android), so we decided to change this in #59 but it, apparently, hasn't been done yet.

Anyway, thank you for your PR but I believe this is not the optimal solution. You may want to check the X-Forwarded-Proto header (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto) first, to decide whether to use `http://` or `https://` in order to properly support proxies. tusd also supports the Forwarded header (https://github.com/tus/tusd/blob/master/unrouted_handler.go#L714-L750), which could also be helpful for you.

> I wonder if we should loosen up the protocol instead tho in this regard. Interested to hear what @Acconut thinks of this. IIRC there was talk once about officially supporting completely relative paths (so /files/xxx) but perhaps we never poured that into protocol. 

In fact, the protocol does allow absolute and relative URLs :) From the spec:

> The Server MUST set the Location header to the URL of the created resource. This URL MAY be absolute or relative.

It does not mention protocol-relative URLs but I have never seen them outside of tus-node-server for the Location header.

**Comment by kvz** [comment]
> In fact, the protocol does allow absolute and relative URLs :) From the spec:

Ah okay, thanks for correcting me! 👌 All good then

**Comment by erikhandersson** [comment]
I see. Thanks.

**Pull request closed without merging**
